#!/bin/sh
cp ../c_header_thing/thing.py ./cthing.py
cp ../c_header_thing/template.py ./template.py
cp ..//emf_pdf_parsing_stuff/manual.py .
./parse_c_stuff.sh
python3 ../emf_pdf_parsing_stuff/generate.py ../emf_pdf_parsing_stuff/contents.txt
cp ../emf_pdf_parsing_stuff/output.py ./autogenerated.py
python3 header.py
python3 parser.py

