#!/bin/sh
cp ../emf_pdf_parsing_stuff/manual.py .
cp ../c_header_thing/thing.py ./cthing.py
cp ../c_header_thing/template.py ./template.py
cp ..//emf_pdf_parsing_stuff/manual.py .
./parse_c_stuff.sh
cd ../emf_pdf_parsing_stuff/
python3 generate.py contents.txt
cd ../emf_parser/
cp ../emf_pdf_parsing_stuff/output.py ./autogenerated.py
python3 header.py
python3 parser.py

